### ISSUE TITLE
安装依赖报错 无法使用

### ISSUE THREAD

**Issue by HappyLeiLei** [royhua/g6-editor-vue#1]
yarn 方法安装 报错内容
error An unexpected error occurred: "http://nexus.industics.com:8081/repository/npm-dev/async-validator/-/async-validator-1.8.5.tgz: ETIMEDOUT".

npm 方法安装 报错内容
gyp ERR! configure error
gyp ERR! stack Error: Client network socket disconnected before secure TLS connection was established
gyp ERR! stack     at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
gyp ERR! stack     at Object.onceWrapper (events.js:273:13)
gyp ERR! stack     at TLSSocket.emit (events.js:187:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1092:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/happy/www/Git/g6-editor-vue-master/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/happy/www/Git/g6-editor-vue-master/node_modules/node-sass
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by royhua** [comment]
把项目下面的，yarn.lock文件删掉，重新安装依赖

**Comment by HappyLeiLei** [comment]
好的 非常感谢
